### ISSUE TITLE
Duplicate comments in source code

### ISSUE THREAD

**Issue by coballast** [coballast/threejs-browserify-conversion-utility#4] opened 2015-03-07 21:14 UTC
Right now, line comments are duplicated on more than one line in output code. I suspect that this may be a bug with either escodegen or esprima.

**Comment by coballast** [comment] 2015-03-07 21:15
Also, block comments are ignored and are not copied to output. Might be related.

**Comment by kumavis** [comment] 2015-03-10 19:56
Here are github issues searches for 'comment':
[esprima](https://github.com/jquery/esprima/search?q=comment&state=open&type=Issues&utf8=%E2%9C%93)
[escodegen](https://github.com/estools/escodegen/search?q=comment&state=open&type=Issues&utf8=%E2%9C%93)

Looks like there are some standing problems here.

I couldn't reproduce it here -- should have just tried the actual conversion utility.
http://requirebin.com/?gist=8eeafa9f1c12a4903a56

A simple test might be just be code -> ast -> code -> ast, then compare ast's -- they should match.
From there we can boil down a minimal case for a bug report

**Comment by kumavis** [comment] 2015-03-12 18:12
Here is an example of the comment weirdness from the top of the `Three.js` file

ours:
```js
var /**
 * @author mrdoob / http://mrdoob.com/
 */
THREE = {
	REVISION: '70'
}; // browserify support
if ( // browserify support
	typeof module === 'object' ) {

	module.exports = THREE;

} // polyfills
if ( // polyfills
	Math.sign === undefined ) {

	Math.sign = function(x) {

		return x < 0 ? -1 : x > 0 ? 1 : 0;

	};

} // https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent.button
// https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent.button
THREE.MOUSE = {
	LEFT: 0,
	MIDDLE: 1,
	RIGHT: 2
}; // GL STATE CONSTANTS
// GL STATE CONSTANTS
```

original:
```js
// File:src/Three.js

/**
 * @author mrdoob / http://mrdoob.com/
 */

var THREE = { REVISION: '70' };

// browserify support

if ( typeof module === 'object' ) {

	module.exports = THREE;

}

// polyfills

if ( Math.sign === undefined ) {

	Math.sign = function ( x ) {

		return ( x < 0 ) ? - 1 : ( x > 0 ) ? 1 : 0;

	};

}
```

**Comment by kumavis** [comment] 2015-03-13 18:37
Got it working in requirebin http://requirebin.com/?gist=23ab7458059f459eb956

I'll come up with a more minimal example and report the bug.

**Comment by kumavis** [comment] 2015-03-13 18:48
woah the comment positioning is really weird...

This sets the comment as a trailing comment for the `1+2` expression, AND a leading comment to the WHOLE if-statement.
```js
1+2
// browserify support

if ( typeof module === "object" ) {

}
```
Here i added content to the if statement's consequent. This sets the comment as a trailing comment for the `1+2` expression, AND a leading comment to the TEST of the if-statement. Weird!
```js
1+2
// browserify support

if ( typeof module === "object" ) {
    module.exports = THREE;
}
```

**Comment by coballast** [comment] 2015-03-13 19:10
You are awesome. Thank you so much!

**Comment by kumavis** [comment] 2015-03-13 19:33
So comments seem to be a really tricky item even on the parsing side. No one can agree on how its supposed to work and there are endless edgecases. Its just algorithmically complicated. Here's an issue I filed for the duplicated comments on the parsing side. Not even sure if its a bug or feature. https://github.com/jquery/esprima/issues/1117

They're discussing a means for external comment processing https://github.com/jquery/esprima/issues/1068.

FWIW that feature was merged into `espree` https://github.com/eslint/espree/pull/66
I've never used it before. I guess we should experiment with `espree` `acorn` and any others that attempt to produce the same ast. whatever solves the problem. `acorn` is what `browserify` uses deep in its depths. `browserify > module-deps > detective > acorn`

**Comment by kumavis** [comment] 2015-03-13 19:48
seems `espree` is subject to the same bug. `acorn` however seems to work great! It requires a little extra setup.
```js
var comments = [], tokens = [];

var ast = parse(src, {
    // collect ranges for each node
    ranges: true,
    // collect comments in Esprima's format
    onComment: comments,
    // collect token ranges
    onToken: tokens
});

escodegen.attachComments(ast, comments, tokens);
var newCode = escodegen.generate(ast, {comment: true})
```

**Comment by coballast** [comment] 2015-03-13 20:16
If it's good enough for browserify, it's good enough for me. Want to make a fork and try it out?

**Closed** 2015-03-13 20:41 UTC
Labels: bug
